:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Presentation
dotnet build src\Presentation
echo Now, run the following to start the project: dotnet run -p src\Presentation\Presentation.csproj --launch-profile web.
echo.
