/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace RestService.Models;

/// <summary>
/// </summary>
[DataContract]
public class Terminal : IEquatable<Terminal>
{
    /// <summary>
    ///     Gets or Sets Id
    /// </summary>
    [DataMember(Name = "id", EmitDefaultValue = true)]
    public Guid Id { get; set; }

    /// <summary>
    ///     Gets or Sets Name
    /// </summary>
    [DataMember(Name = "Name", EmitDefaultValue = false)]
    public string Name { get; set; }

    /// <summary>
    ///     Gets or Sets Token
    /// </summary>
    [DataMember(Name = "Token", EmitDefaultValue = false)]
    public string Token { get; set; }

    /// <summary>
    ///     Gets or Sets ExpiredTokenOn
    /// </summary>
    [DataMember(Name = "ExpiredTokenOn", EmitDefaultValue = true)]
    public DateOnly ExpiredTokenOn { get; set; }

    /// <summary>
    ///     Returns true if Terminal instances are equal
    /// </summary>
    /// <param name="other">Instance of Terminal to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Terminal other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;

        return
            (
                Id == other.Id ||
                Id.Equals(other.Id)
            ) &&
            (
                Name == other.Name ||
                (Name != null &&
                 Name.Equals(other.Name))
            ) &&
            (
                Token == other.Token ||
                (Token != null &&
                 Token.Equals(other.Token))
            ) &&
            (
                ExpiredTokenOn == other.ExpiredTokenOn ||
                ExpiredTokenOn.Equals(other.ExpiredTokenOn)
            );
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Terminal {\n");
        sb.Append("  Id: ").Append(Id).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Token: ").Append(Token).Append("\n");
        sb.Append("  ExpiredTokenOn: ").Append(ExpiredTokenOn).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (obj is null) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((Terminal)obj);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)

            hashCode = hashCode * 59 + Id.GetHashCode();
            if (Name != null)
                hashCode = hashCode * 59 + Name.GetHashCode();
            if (Token != null)
                hashCode = hashCode * 59 + Token.GetHashCode();

            hashCode = hashCode * 59 + ExpiredTokenOn.GetHashCode();
            return hashCode;
        }
    }

    #region Operators

#pragma warning disable 1591

    public static bool operator ==(Terminal left, Terminal right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(Terminal left, Terminal right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591

    #endregion Operators
}