/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#region

using System.Threading.Tasks;
using Business.Secure.AccessScope.Interfaces;
using Domain.AccessScope.Actions.Abstractions;
using Microsoft.AspNetCore.Mvc;
using RestService.Models;
using Swashbuckle.AspNetCore.Annotations;

#endregion

namespace RestService.Controllers;

/// <summary>
/// </summary>
[ApiController]
public class TerminalAccessControlApiController : ControllerBase
{
    private readonly IAccessControlTerminalServiceSecure _service;


    public TerminalAccessControlApiController(IAccessControlTerminalServiceSecure service)
    {
        _service = service;
    }


    /// <summary>
    ///     Verifies employee access to the facility through the terminal.
    /// </summary>
    /// <param name="request"></param>
    /// <response code="200">Boolean value denoting access.</response>
    [HttpPost]
    [Route("/access/verify-terminal")]
    [Consumes("application/json")]
    [SwaggerOperation("VerifyAccessViaTerminal")]
    [SwaggerResponse(200, type: typeof(bool), description: "Boolean value denoting access.")]
    public async Task<IActionResult> VerifyAccessViaTerminal([FromBody] VerifyAccessViaTerminalRequest request)
    {
        var model = new VerifyAccessModel(
            request.UserId,
            request.FacilityId
        );

        return Ok(await _service.VerifyAccessAsync(model));
    }
}