/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.ComponentModel.DataAnnotations;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class CategoryAccessControlManagementApiController : ControllerBase
    {
        /// <summary>
        ///     Gets a list of categories to which the user has access.
        /// </summary>
        /// <param name="userId"></param>
        /// <response code="200">List of categories to which the user has access.</response>
        [HttpGet]
        [Route("/users/{user_id}/access/categories")]
        [SwaggerOperation("GetAccessUserCategories")]
        [SwaggerResponse(statusCode: 200, type: typeof(Category),
            description: "List of categories to which the user has access.")]
        public IActionResult GetAccessUserCategories([FromRoute(Name = "user_id")] [Required] string userId)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///     Creates user access to a category.
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="grantUserAccessCategoryRequest"></param>
        /// <response code="200">Access to the category issued.</response>
        [HttpPost]
        [Route("/users/{user_id}/access/categories")]
        [Consumes("application/json")]
        [SwaggerOperation("GrantUserAccessCategory")]
        public IActionResult GrantUserAccessCategory(
            [FromRoute(Name = "user_id")] [Required]
            string userId,
            [FromBody] GrantUserAccessCategoryRequest grantUserAccessCategoryRequest
        )
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///     Removes category access from the user.
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="categoryId"></param>
        /// <response code="200">Access to the category has been successfully removed.</response>
        [HttpDelete]
        [Route("/users/{user_id}/access/categories/{category_id}")]
        [SwaggerOperation("RevokeUserAccessCategory")]
        public IActionResult RevokeUserAccessCategory(
            [FromRoute(Name = "user_id")] [Required]
            string userId,
            [FromRoute(Name = "category_id")] [Required]
            string categoryId)
        {
            throw new NotImplementedException();
        }
    }
}