/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#region

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using FacilityAccessService.Business.FacilityScope.Actions;
using FacilityAccessService.Domain.Secure.FacilityScope.Interfaces;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

#endregion

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class FacilityManagementApiController : ControllerBase
    {
        private readonly IFacilityServiceSecure _service;


        public FacilityManagementApiController(IFacilityServiceSecure service)
        {
            _service = service;
        }

        /// <summary>
        ///     Creates a facility and returns it.
        /// </summary>
        /// <param name="request"></param>
        /// <response code="200">Facility.</response>
        [HttpPost]
        [Route("/facilities")]
        [Consumes("application/json")]
        [SwaggerOperation("CreateFacility")]
        [SwaggerResponse(200, type: typeof(Facility), description: "Facility.")]
        public async Task<IActionResult> CreateFacility([FromBody] CreateFacilityRequest request)
        {
            var model = new CreateFacilityModel(
                Name: request.Name,
                Description: request.Description
            );

            return Ok(await _service.CreateFacilityAsync(model));
        }

        /// <summary>
        ///     Deletes facility by id.
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200">Facility successfully deleted.</response>
        [HttpDelete]
        [Route("/facilities/{id}")]
        [SwaggerOperation("DeleteFacility")]
        public async Task<IActionResult> DeleteFacility([FromRoute(Name = "id")] [Required] string id)
        {
            var model = new DeleteFacilityModel(Guid.Parse(id));

            await _service.DeleteFacilityAsync(model);

            return Ok();
        }

        /// <summary>
        ///     Returns all facilities according to the conditions.
        /// </summary>
        /// <param name="take"></param>
        /// <param name="offset"></param>
        /// <param name="name"></param>
        /// <response code="200">A list of facilities that match the provided query parameters.</response>
        [HttpGet]
        [Route("/facilities")]
        [SwaggerOperation("GetAllFacilities")]
        [SwaggerResponse(200, type: typeof(List<Facility>),
            description: "A list of facilities that match the provided query parameters.")]
        public IActionResult GetAllFacilities(
            [FromQuery(Name = "take")] [Required] [Range(1, 100)]
            int take,
            [FromQuery(Name = "offset")] [Required]
            int offset, [FromQuery(Name = "name")] string name
        )
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///     Updates a facility partially.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="request"></param>
        /// <response code="200">Facility successfully updated.</response>
        [HttpPatch]
        [Route("/facilities/{id}")]
        [Consumes("application/json")]
        [SwaggerOperation("UpdateFacility")]
        [SwaggerResponse(200, type: typeof(Facility), description: "Facility successfully updated.")]
        public async Task<IActionResult> UpdateFacility(
            [FromRoute(Name = "id")] [Required] Guid id,
            [FromBody] UpdateFacilityRequest request
        )
        {
            var model = new UpdateFacilityModel(
                FacilityId: id,
                Name: request.Name,
                Description: request.Description
            );

            return Ok(await _service.UpdateFacilityAsync(model));
        }
    }
}