/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class FacilityManagementApiController : ControllerBase
    {
        /// <summary>
        ///     Creates a facility and returns it.
        /// </summary>
        /// <param name="createFacilityRequest"></param>
        /// <response code="200">Facility.</response>
        [HttpPost]
        [Route("/facilities")]
        [Consumes("application/json")]
        [SwaggerOperation("CreateFacility")]
        [SwaggerResponse(statusCode: 200, type: typeof(Facility), description: "Facility.")]
        public IActionResult CreateFacility([FromBody] CreateFacilityRequest createFacilityRequest)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///     Deletes facility by id.
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200">Facility successfully deleted.</response>
        [HttpDelete]
        [Route("/facilities/{id}")]
        [SwaggerOperation("DeleteFacility")]
        public IActionResult DeleteFacility([FromRoute(Name = "id")] [Required] string id)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///     Returns all facilities according to the conditions.
        /// </summary>
        /// <param name="take"></param>
        /// <param name="offset"></param>
        /// <param name="name"></param>
        /// <response code="200">A list of facilities that match the provided query parameters.</response>
        [HttpGet]
        [Route("/facilities")]
        [SwaggerOperation("GetAllFacilities")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Facility>),
            description: "A list of facilities that match the provided query parameters.")]
        public IActionResult GetAllFacilities(
            [FromQuery(Name = "take")] [Required] [Range(1, 100)]
            int take,
            [FromQuery(Name = "offset")] [Required]
            int offset, [FromQuery(Name = "name")] string name
        )
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///     Updates a facility partially.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="updateFacilityRequest"></param>
        /// <response code="200">Facility successfully updated.</response>
        [HttpPatch]
        [Route("/facilities/{id}")]
        [Consumes("application/json")]
        [SwaggerOperation("UpdateFacility")]
        [SwaggerResponse(statusCode: 200, type: typeof(Facility), description: "Facility successfully updated.")]
        public IActionResult UpdateFacility(
            [FromRoute(Name = "id")] [Required] string id,
            [FromBody] UpdateFacilityRequest updateFacilityRequest
        )
        {
            throw new NotImplementedException();
        }
    }
}