/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class GuardAccessControlApiController : ControllerBase
    {
        /// <summary>
        ///     Verifies employee access to the facility through the guarder.
        /// </summary>
        /// <param name="verifyAccessViaTerminalRequest"></param>
        /// <response code="200">Boolean value denoting access.</response>
        [HttpPost]
        [Route("/access/verify-guard")]
        [Consumes("application/json")]
        [SwaggerOperation("VerifyAccessViaGuard")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool), description: "Boolean value denoting access.")]
        public IActionResult VerifyAccessViaGuard(
            [FromBody] VerifyAccessViaTerminalRequest verifyAccessViaTerminalRequest
        )
        {
            throw new NotImplementedException();
        }
    }
}