/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Threading.Tasks;
using FacilityAccessService.Business.AccessScope.Actions;
using FacilityAccessService.Business.AccessScope.Actions.Abstractions;
using FacilityAccessService.Business.AccessScope.Services;
using FacilityAccessService.Domain.Secure.AccessScope.Interfaces;
using FacilityAccessService.Domain.Secure.CommonScope.Context;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class GuardAccessControlApiController : ControllerBase
    {
        private readonly IAccessControlGuardServiceSecure _service;


        public GuardAccessControlApiController(IAccessControlGuardServiceSecure service)
        {
            this._service = service;
        }

        /// <summary>
        ///     Verifies employee access to the facility through the guarder.
        /// </summary>
        /// <param name="request"></param>
        /// <response code="200">Boolean value denoting access.</response>
        [HttpPost]
        [Route("/access/verify-guard")]
        [Consumes("application/json")]
        [SwaggerOperation("VerifyAccessViaGuard")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool), description: "Boolean value denoting access.")]
        public async Task<IActionResult> VerifyAccessViaGuard(
            [FromBody] VerifyAccessViaTerminalRequest request
        )
        {
            var model = new VerifyAccessModel(
                UserId: request.UserId,
                FacilityId: Guid.Parse(request.FacilityId));

            return Ok(await _service.VerifyAccessAsync(model));
        }
    }
}