/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#region

using System.Threading.Tasks;
using FacilityAccessService.Business.AccessScope.Actions.Abstractions;
using FacilityAccessService.Domain.Secure.AccessScope.Interfaces;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

#endregion

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    public class GuardAccessControlApiController : ControllerBase
    {
        private readonly IAccessControlGuardServiceSecure _service;


        public GuardAccessControlApiController(IAccessControlGuardServiceSecure service)
        {
            _service = service;
        }


        /// <summary>
        ///     Verifies employee access to the facility through the guarder.
        /// </summary>
        /// <param name="request"></param>
        /// <response code="200">Boolean value denoting access.</response>
        [HttpPost]
        [Route("/access/verify-guard")]
        [Consumes("application/json")]
        [SwaggerOperation("VerifyAccessViaGuard")]
        [SwaggerResponse(200, type: typeof(bool), description: "Boolean value denoting access.")]
        public async Task<IActionResult> VerifyAccessViaGuard([FromBody] VerifyAccessViaTerminalRequest request)
        {
            var model = new VerifyAccessModel(
                request.UserId,
                request.FacilityId
            );

            return Ok(await _service.VerifyAccessAsync(model));
        }
    }
}