/*
 * Facility Access Service API
 *
 * The service an access control system for facilities within the enterprise territory.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Threading.Tasks;
using FacilityAccessService.Business.AccessScope.Actions;
using FacilityAccessService.Business.AccessScope.Actions.Abstractions;
using FacilityAccessService.Business.TerminalScope.ValueObjects;
using FacilityAccessService.Domain.Secure.AccessScope.Interfaces;
using FacilityAccessService.RestService.Authentication.Attributes;
using FacilityAccessService.RestService.Models;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace FacilityAccessService.RestService.Controllers
{
    /// <summary>
    /// </summary>
    [ApiController]
    [AllowAnonymous]
    public class TerminalAccessControlApiController : ControllerBase
    {
        private readonly IAccessControlTerminalServiceSecure _service;

        public TerminalAccessControlApiController(IAccessControlTerminalServiceSecure service)
        {
            this._service = service;
        }


        /// <summary>
        ///     Verifies employee access to the facility through the terminal.
        /// </summary>
        /// <param name="terminalAccessToken"></param>
        /// <param name="request"></param>
        /// <response code="200">Boolean value denoting access.</response>
        [HttpPost]
        [Route("/access/verify-terminal")]
        [Consumes("application/json")]
        [SwaggerOperation("VerifyAccessViaTerminal")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool), description: "Boolean value denoting access.")]
        public async Task<IActionResult> VerifyAccessViaTerminal(
            [FromHeader] string terminalAccessToken,
            [FromBody] VerifyAccessViaTerminalRequest request
        )
        {
            var model = new VerifyAccessModel(
                UserId: request.UserId,
                FacilityId: Guid.Parse(request.FacilityId)
            );

            return Ok(await _service.VerifyAccessAsync(model));
        }
    }
}